version: '3.8'
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-cli-rest-api
    ports:
      - "8080:8080"
    environment:
      - MODE=json-rpc
    volumes:
      - ./signal-cli-data:/home/.local/share/signal-cli

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=signaltrader
      - POSTGRES_PASSWORD=your_secure_password  # Replace with your password
      - POSTGRES_DB=signaltrader_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  signal-bot:
    build: .
    container_name: signal-bot
    depends_on:
      - signal-cli-rest-api
      - postgres
    environment:
      - SIGNAL_SERVICE_HOST=signal-cli-rest-api
      - SIGNAL_SERVICE_PORT=8080
      - PHONE_NUMBER=+18122433247  # Replace with your number
      - DEVICE_NAME=SignalBot
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=signaltrader_db
      - DB_USER=signaltrader
      - DB_PASSWORD=your_secure_password

  db-daemon:
    build: .
    container_name: db-daemon
    command: python daemon.py
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=signaltrader_db
      - DB_USER=signaltrader
      - DB_PASSWORD=your_secure_password

volumes:
  pgdata: